name: CI
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup do Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Dando permissao ao mvnw
        run: chmod +x mvnw
      - name: Build com Maven
        run: ./mvnw clean package -DskipTests